# Este notebook lo usé para hacer el tratamiento faltante del dataframe con la data ya extraída de los hits 

En esencia, el código contenido en este notebook lo utilicé para agregar las columnas faltantes azimut y zenit al dataframe que contenía ya TODOS los hits extraídos de TODOS los archivos, los cuales coincidían en linea y piso detector con los selected pulses de cada evento.

Cabe aclarar que el dataframe resultantes es bastante "grande", de aprox. 11GB.

Referencias:
* https://medium.com/dunder-data/selecting-subsets-of-data-in-pandas-6fcd0170be9c
* https://medium.com/@juan.7655/cleansing-messy-excel-files-with-pandas-95a2ba3d8b2d
* https://cmdlinetips.com/2018/02/how-to-subset-pandas-dataframe-based-on-values-of-a-column/
* https://datatofish.com/convert-pandas-dataframe-to-list/
* https://www.geeksforgeeks.org/python-pandas-dataframe-insert/

In [1]:
import pandas as pd
import math
import timeit

#path = "U:\MASTER INT. ARTIFICIAL\TFM_DATA\CLEANDATA\\" #Path para mi laptop en casa
path = "F:\\DATA_TFM\\CLEANDATA\\" #Path para mi PC en el trabajo

#archivo = "data_aafit_bbfit_muon.csv"
archivo = "data_best_hits_full.csv"

file = path+archivo

In [2]:
#Necesito calcular azimut y zenit para el dataframe que ya obtuve de los hits

df = pd.read_csv(file)

#En cargar el df en la laptop tarda alrededor de 5 min, se debe tener cuidado, verificando el CPU de la máquina,
#llega a calentarse hasta 70°C, lo que en una laptop puede dañarla si se mantiene mucho tiempo así.
#en la PC Desktop del trabajo solo llega hasta 35°C lo cual es muy bueno.

In [3]:
#Generando un "chunk" del df principal para solo hacer la demostración de insertar azimut y zenit

#### Hay que ejecutar la celda de validación más abajo **** mucho ojo con esto para la prueba ****

In [4]:
#Calculo del azimut y zenit para cada row del dataframe

col_azimut=[];col_zenit=[]

for i in range(len(df)):
    if i % 1000000 == 0:
        print (i)
    #Obteniendo los valores
    X = df.iloc[i]['X']; Y = df.iloc[i]['Y']; Z = df.iloc[i]['Z']
    #print("%.6f" %X, "%.6f" %Y, "%.6f" %Z)
    #print("X:%.4f", %X)
    #Calculando el azimut de la fila
    azimut=math.atan2(Y,X)
    #Calculando el zenit de la fila
    zenit = math.acos(Z)
    #print("azimut: %.6f" %azimut, "zenit: %.6f" %zenit)
    col_azimut.append(azimut)
    col_zenit.append(zenit)

print(len(col_azimut),len(col_zenit))

#No es bueno imprimir la salida de i en cada bucle mejor cada millón, ya que
#se alenta mucho el notebook, pienso que es porque se acaba la memoria de video al etar imprimiendo i

0
1000000
2000000
3000000
4000000
5000000
6000000
7000000
8000000
9000000
10000000
11000000
12000000
13000000
14000000
15000000
16000000
17000000
18000000
19000000
20000000
21000000
22000000
23000000
24000000
25000000
26000000
27000000
28000000
29000000
30000000
31000000
32000000
33000000
34000000
35000000
36000000
37000000
38000000
39000000
40000000
41000000
42000000
43000000
44000000
45000000
46000000
47000000
48000000
49000000
50000000
51000000
52000000
53000000
54000000
55000000
56000000
57000000
58000000
59000000
60000000
61000000
62000000
63000000
63520301 63520301

In [5]:
#Insertando la data de azimut y zenit al df completo de 60M de líneas
df.insert(15,'azimut',col_azimut)
df.insert(16,'zenit',col_zenit)

In [6]:
#Grabamos el df ya con la data de azimut y zenit como un CSV

#outputpath = "U:\MASTER INT. ARTIFICIAL\TFM_DATA\CLEANDATA\\"
outputpath = "F:\DATA_TFM\CLEANDATA\\"
    
df.to_csv(outputpath+"data_best_hits_completo.csv", index = None)#, header=None)

In [7]:
df.shape

(63520301, 20)

In [8]:
df.sample(10)

,runID,frameID,trigger_counter,interactionID,hit,#hit,lin_det,piso_det,mód_opt,X',Y',Z',X,Y,Z,azimut,zenit,tiempo,amp,frec_hits
60997434,84640,260517,750,2,hit,14,4,5,1,44.478364,9.849635,-113.395434,-0.595723,0.380939,-0.707106,2.572665,2.356193,-1849.641320,0.868721,189.094543
31654842,59580,81478,1186,1,hit,30,6,19,1,91.769083,-22.773227,90.742566,-0.351424,-0.613598,-0.707106,-2.090921,2.356193,191.531674,2.363182,72.479248
52151597,76400,68340,66,1,hit,34,8,12,2,11.675714,-38.460392,-10.760434,0.329604,0.625589,-0.707106,1.085885,2.356193,155.493014,2.115262,144.920349
33541661,60690,66424,3466,1,hit,57,6,7,2,91.546720,-22.544388,-83.519434,-0.623430,-0.333670,-0.707106,-2.650170,2.356193,-746.562785,1.178225,52.299500
48165485,70980,325153,25,2,hit,186,3,16,0,-9.501412,37.265113,46.433566,0.577797,-0.407616,-0.707106,-0.614385,2.356193,204.268239,0.545427,409.622192
15652664,45960,76480,2606,1,hit,136,11,22,2,-79.246948,-58.288879,133.715566,-0.676865,-0.204584,-0.707106,-2.848071,2.356193,678.708404,22.394747,46.787262
27268757,55950,34319,521,1,hit,371,1,6,2,4.461160,96.139954,-107.379434,0.128347,-0.695361,-0.707106,-1.388274,2.356193,141.907411,1.488986,74.176788
24482168,53900,18828,5069,2,hit,38,6,21,2,91.478671,-22.252221,119.800566,-0.706707,0.023788,-0.707106,3.107945,2.356193,883.869359,20.919523,53.443909
31779097,59620,10211,94,1,hit,89,3,8,0,-9.433206,37.393520,-69.780434,0.661238,-0.250528,-0.707106,-0.362166,2.356193,145.934796,1.514411,75.740814
32180794,59880,17275,1830,2,hit,174,8,6,2,11.518029,-39.538736,-97.924434,0.136751,-0.693758,-0.707106,-1.376175,2.356193,210.205262,2.040628,71.849823

## Pruebas que hice para insertar las columnas azimut y zenit

In [ ]:
#Prueba para insertar la columna azimut y zenit a un "chunk" del df principal
tempdf.insert(15,'azimut',col_azimut)
tempdf.insert(16,'zenit',col_zenit)

#tempdf = tempdf.drop(columns=['azimut']) #Por si quiero borrar la columna
tempdf

In [ ]:
#Viendo como quedo la columna
tempdf

In [ ]:
#tempdf.insert(14,'azimut', -3*math.pi)

# Verificación Aleatoria

Como punto de verificación aleatorio de que la selección de hits ha sido correcta, podemos ejecutar la celda siguiente y cambiar parámetros. Debemos también abrir el archivo correspondiente y verificar manualmente (usando Excel).

Puede ser tedioso, pero haciéndolo al azar, podemos verificar que el algoritmo se ejecutó correctamente y no hay errores.

In [ ]:
#Verificación Aleatoria
#Búsqueda de un runID y frameID específico, sólo como verificación aleatoria del algoritmo

runID = 55920; interactionID = 2; frameID = 25429
tempdf = df.loc[df['runID'] == runID]
tempdf = tempdf.loc[tempdf['interactionID']== interactionID]
tempdf = tempdf.loc[tempdf['frameID']==frameID]

print(tempdf.shape)
tempdf.head(10)
#tempdf.sort_values(['frameID'])

In [ ]:
#Como ya se que trabajar con listas es mucho más rápido que con dataframes, intentaré eso precisamente
#pasaré a una lista el dataframe y veré como me va para generar el algoritmo que haga la transformación.

#lista = df.values.tolist() #Esta simple instrucción se come la memoria horriblemente!!!

### OOOoooops... se comió toda la memoria XD... casi hago que vuelva a hacer crash!!!

In [ ]:
#Prueba de tiempo para saber cuanto tarda el obtener los datos para el calculo de azimut y zenit

#%timeit type(df.iloc[0]['X']) #Este fue el comando que utilicé
#Y de acuerdo a mis calculos, 

df.shape

tiempo = 177 * 33000000
print(tiempo/1000000/60)

## Eliminación de las columnaz X, Y y Z del dataframe resultante

In [1]:
import pandas as pd
import math

#path = "U:\MASTER INT. ARTIFICIAL\TFM_DATA\CLEANDATA\\" #Path para mi laptop en casa
path = "F:\\DATA_TFM\\CLEANDATA\\" #Path para mi PC en el trabajo

archivo = "data_best_hits_completo.csv"

file = path+archivo

df_limpio = pd.read_csv(file)

In [2]:
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63520301 entries, 0 to 63520300
Data columns (total 20 columns):
runID              int64
frameID            int64
trigger_counter    int64
interactionID      int64
hit                object
#hit               int64
lin_det            int64
piso_det           int64
mód_opt            int64
X'                 float64
Y'                 float64
Z'                 float64
X                  float64
Y                  float64
Z                  float64
azimut             float64
zenit              float64
tiempo             float64
amp                float64
frec_hits          float64
dtypes: float64(11), int64(8), object(1)
memory usage: 9.5+ GB

In [3]:
#Eliminación de las columnas X, Y y Z

df_limpio = df_limpio.drop(columns=['hit','X','Y','Z'])

In [4]:
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63520301 entries, 0 to 63520300
Data columns (total 16 columns):
runID              int64
frameID            int64
trigger_counter    int64
interactionID      int64
#hit               int64
lin_det            int64
piso_det           int64
mód_opt            int64
X'                 float64
Y'                 float64
Z'                 float64
azimut             float64
zenit              float64
tiempo             float64
amp                float64
frec_hits          float64
dtypes: float64(8), int64(8)
memory usage: 7.6 GB

In [5]:
df_limpio.to_csv(path+"df_best_hits_limpio.csv")

In [6]:
df_limpio.sample(10)

,runID,frameID,trigger_counter,interactionID,#hit,lin_det,piso_det,mód_opt,X',Y',Z',azimut,zenit,tiempo,amp,frec_hits
37494165,62440,32739,1190,2,298,9,16,0,-94.734647,8.303105,46.595566,-2.412176,2.356193,211.565887,2.597402,167.999268
48573946,71450,19209,923,2,76,7,24,0,-35.468594,-15.672658,163.344566,-0.507616,2.356193,2170.259520,0.991379,130.939484
52706353,77410,326393,1064,1,166,6,11,0,91.778930,-21.764589,-25.402434,2.071291,2.356193,2325.310886,1.002631,62.084198
45933964,69020,6964,1428,1,247,8,10,1,11.153228,-38.452097,-39.791434,2.023960,2.356193,765.521836,2.725289,140.876770
36272437,61830,43961,4545,2,300,9,9,2,-93.913947,8.261568,-54.998434,-0.830595,2.356193,958.602065,0.845898,56.114197
19714313,50700,106287,1397,1,147,4,10,1,44.448636,9.797326,-40.735434,2.676815,2.356193,670.406666,0.943915,112.323761
46643096,69260,9512,1111,1,329,6,5,1,92.444199,-21.843272,-112.557434,0.834930,2.356193,306.721828,0.702846,79.078674
17269425,47830,26497,1601,2,119,8,14,0,11.922524,-39.231666,18.272566,-0.466515,2.356193,1268.595643,5.632499,63.419342
6518679,34420,34310,677,2,228,10,19,0,59.952527,-79.503925,90.740108,-1.823185,2.356193,268.477349,1.710829,70.056915
56297810,82830,87843,1254,2,189,1,25,1,3.789889,96.593357,168.632566,-2.941420,2.356193,414.212175,1.295874,45.337677